version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    driver: bridge

volumes:
  postgres-storage:
  pgadmin-storage:

services:
  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testDB
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root@123
    ports:
      - 5432:5432
    networks:
      - web-app-net
    volumes:
      - postgres-storage:/var/lib/postgresql/data
      - ./conf/postgresdb.sql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mypage.com
      PGADMIN_DEFAULT_PASSWORD: root@123
    volumes:
      - pgadmin-storage:/var/lib/pgadmin
    restart: on-failure
    networks:
      - web-app-net
    depends_on:
      - postgres-db

#Use host.docker.internal instead of localhost for the PgAdmin HostName/Address running inside the Docker

#end of scripts
